import Image from "next/image";
import SlideMenu from '../ui/components/userform/SlideMenu';
import Head from 'next/head';
import styles from './Home.module.css'; 

export default function Home() {
  return (
    <div>
      <SlideMenu />
      <div className={styles.container}>
        <Head>
          <title>My Casino App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div><h1>My Casino</h1></div>
        <section className={styles.bannerSection}>
          <div className={styles.bannerItem}>
            <Image src="/image/banner 1.jpg" alt="Banner 1" width={500} height={100} />
          </div>
          <div className={styles.bannerItem}>
            <Image src="/image/banner 2.jpg" alt="Banner 2" width={500} height={100} />
          </div>
          <div className={styles.bannerItem}>
            <Image src="/image/banner 3.jpg" alt="Banner 3" width={500} height={100} />
          </div>
          <div className={styles.bannerItem}>
            <Image src="/image/banner 4.jpg" alt="Banner 4" width={500} height={100} />
          </div>
          <div className={styles.bannerItem}>
            <Image src="/image/banner 5.jpg" alt="Banner 5" width={500} height={100} />
          </div>
        </section>

        <main className={styles.main}>
          <section className={styles.banner}>
            <Image src="/image/Poker banner.jpg" alt="Banner" width={500} height={300} />
          </section>

          <section className={styles.gameSection}>
            <h2>แนะนำ</h2>
            <div className={styles.gameList}>
              <div className={styles.gameItem}>
                <Image src="/image/poker.jpg" alt="Poker" width={200} height={200} />
                <p>Poker</p>
              </div>
              <div className={styles.gameItem}>
                <Image src="/image/slots.jpg" alt="Slots" width={200} height={200} />
                <p>Slots</p>
              </div>
              <div className={styles.gameItem}>
                <Image src="/image/blackjack.jpg" alt="Blackjack" width={200} height={200} />
                <p>Blackjack</p>
              </div>
            </div>
          </section>

          <section className={styles.promotionSection}>
            <h2>Promotions</h2>
            <div className={styles.promotionList}>
              <div className={styles.promotionItem}>
                <Image src="/image/promotion 1.jpg" alt="Promotion 1" width={500} height={100} />
              </div>
              <div className={styles.promotionItem}>
                <Image src="/image/promotion 2.jpg" alt="Promotion 2" width={500} height={100} />
              </div>
            </div>
          </section>
        </main>

        <footer className={styles.footer}>
          <div className={styles.footerContent}>
            <p>Contact Us: xxx-xxx-xxxx</p>
          </div>
        </footer>
      </div>
    </div>
  );
}

